"""add latitude

Revision ID: 8e0dd36e11ec
Revises: 64e2eddfc525
Create Date: 2021-02-02 14:48:42.286718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0dd36e11ec'
down_revision = '64e2eddfc525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'latitude')
    # ### end Alembic commands ###
